notplastic/notplastic_site/models.py
from datetime import timedelta, datetime
import string, random, json, uuid

from sqlalchemy.orm import relationship, foreign
from sqlalchemy import func
from sqlalchemy_sluggable import Sluggable

from flask import url_for, current_app

from notplastic import db, utils, mercadopago_ipn


class DownloadCode(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(12), nullable=False)
    max_downloads = db.Column(db.Integer, default=5)
    is_download_card = db.Column(db.Boolean, default=False)
    mercadopago_collection_id = db.Column(db.Integer, db.ForeignKey('collection.id'))
    project_id = db.Column(db.Integer, db.ForeignKey('project.id'))

    download_tickets = relationship('DownloadTicket', lazy='dynamic', backref='download_code')

    __table_args__ = (db.Index('project_code_idx',
                               'project_id',
                               'code',
                               unique=True),)

    def times_downloaded(self):
        return self.download_tickets.filter(DownloadTicket.downloaded_at != None).count()

    def __unicode__(self):
        return self.code

    @classmethod
    def get_unique_code(cls, project, length=-1):
        if length == -1:
            length = current_app.config.get('DOWNLOAD_CODE_LENGTH', 6)
        rs = lambda: ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(length))
        while True:
            code = rs()
            c = db.session.query(cls) \
                          .filter(cls.code==code) \
                          .filter(cls.project==project) \
                          .count()
            if c == 0:
                return code

class DownloadTicket(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ticket = db.Column(db.String(40), nullable=False, unique=True)
    time_to_live = db.Column(db.Integer, nullable=False, default=24*60*60)
    created_at = db.Column(db.DateTime(), default=func.now())
    downloaded_at = db.Column(db.DateTime())
    download_code_id = db.Column(db.Integer, db.ForeignKey('download_code.id'))

    def has_expired(self, now=None):
        if now is None:
            now = datetime.now()

        return (now - self.created_at).total_seconds() >= self.time_to_live

    @classmethod
    def get_unique_ticket(cls):
        while True:
            t = uuid.uuid1().get_hex()
            c = db.session.query(cls) \
                          .filter(cls.ticket==t) \
                          .count()
            if c == 0:
                return t

class Project(db.Model, Sluggable):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text(), nullable=False)
    description = db.Column(db.Text())
    extended_description = db.Column(db.Text())
    extra_head_html = db.Column(db.Text())
    amount = db.Column(db.Numeric(precision=2))
    max_amount = db.Column(db.Numeric(precision=2), nullable=True)
    suggested_amount = db.Column(db.Numeric(precision=2), nullable=True)
    max_downloads = db.Column(db.Integer, nullable=False, default=5)
    file = db.Column(db.String(255), nullable=False)
    background_image_url = db.Column(db.String(512), nullable=True)
    created_at = db.Column(db.DateTime(), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    download_codes = relationship(DownloadCode, lazy='dynamic', backref='project')
    mp_payment_preferences = relationship('MercadoPagoPaymentPreference', backref='project')

    __sluggable__ = slug_options = {
        'populate_from': 'name'
    }

    def __unicode__(self):
        return "%s" % self.name

    @property
    def is_variable_price(self):
        return self.max_amount is not None

class MercadoPagoPaymentPreference(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey('project.id'))
    payment_preference_id = db.Column(db.String(50))
    amount = db.Column(db.Numeric(precision=2))
    definition = db.Column(db.Text())

    @classmethod
    def save_to_mercadopago(cls, payment_preference):
        if payment_preference.definition is not None:
            # refuse to save if not new
            return

        mp = utils.get_MP_client()
        response = mp.create_preference({
            'items': [
                {
                    'title': payment_preference.project.name,
                    'description': payment_preference.project.description,
                    'quantity': 1,
                    'currency_id': 'ARS',
                    'unit_price': payment_preference.amount,
                }
            ],
            'external_reference': payment_preference.project.id,
            'back_urls': {
                'success': url_for('notplastic_site.payment_confirmation', project=payment_preference.project.slug, status='success', _external=True),
                'failure': url_for('notplastic_site.payment_confirmation', project=payment_preference.project.slug, status='failure', _external=True),
                'pending': url_for('notplastic_site.payment_confirmation', project=payment_preference.project.slug, status='pending', _external=True),
            }
        })

        payment_preference.definition = json.dumps(response['response'])
        payment_preference.payment_preference_id = response['response']['id']

        return payment_preference


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255), nullable=False, unique=True)
    created_at = db.Column(db.DateTime(), default=func.now())

    projects = relationship('Project', lazy='dynamic', backref='user')

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.email)

notplastic/notplastic_site/forms.py
from flask_wtf import Form
from wtforms import TextField
from wtforms.fields.html5 import IntegerRangeField
from wtforms.validators import DataRequired, NumberRange

class DownloadCode(Form):
    download_code = TextField('download_code', validators=[DataRequired()])

class Payment(Form):
    amount = IntegerRangeField('amount', validators=[DataRequired()])

notplastic/notplastic_site/views.py
from datetime import datetime
from urlparse import urlparse
import os, json

from flask import Blueprint, request, abort, send_file, redirect, url_for, render_template, make_response, session, current_app, jsonify
from flask.ext.cors import cross_origin

from notplastic import db, limiter, csrf, utils
from notplastic.mercadopago_ipn import models as mp_models
import models, forms, signal_handlers

mod = Blueprint('notplastic_site',
                __name__,
                url_prefix='/p',
                template_folder='templates',
                static_folder='static')

@mod.route('/oembed')
def oembed():
    """ oEmbed endpoint """
    if request.args.get('url') is None:
        abort(400)

    route, params = utils.route_from(request.args['url'])

    project = db.session.query(models.Project) \
                  .filter(models.Project.slug==params.get('project')) \
                  .first()

    if project is None:
        abort(404)

    resp = {
        'type': 'rich',
        'version': '1.0',
        'title': project.name,
        'provider_name': 'unabanda.cc',
        'provider_url': 'http://unbanda.cc',
        'cache_age': 3600,
        'html': render_template('embed_widget.html',
                                project=project),
        'width': '100%',
        'height': 100
    }

    return jsonify(**resp)

@mod.route('/<project>')
def index(project):
    p = db.session.query(models.Project) \
                  .filter(models.Project.slug==project) \
                  .first()
    if p is None:
        abort(404)

    return render_template('project_landing.html',
                           project=p,
                           download_code_form=forms.DownloadCode(),
                           payment_form=forms.Payment())


@mod.route('/<project>/dl/<ticket>')
def download(project, ticket):
    p = db.session.query(models.Project) \
                  .join(models.DownloadCode) \
                  .join(models.DownloadTicket) \
                  .filter(models.Project.slug==project) \
                  .filter(models.DownloadTicket.ticket==ticket) \
                  .first()

    if p is None:
        abort(404)

    t = db.session.query(models.DownloadTicket) \
                  .join(models.DownloadCode) \
                  .join(models.Project) \
                  .filter(models.DownloadTicket.ticket==ticket) \
                  .first()


    if (t is None) or (t.downloaded_at is not None) or t.has_expired():
        abort(410)

    t.downloaded_at = datetime.now()

    db.session.add(t)
    db.session.commit()

    return send_file(os.path.join(current_app.config['PROJECT_FILES_PATH'],
                                  p.file),
                     as_attachment=True)

@mod.route('/<project>/check_download_code', methods=['POST'])
@limiter.limit('5/minute')
def validate_download_code(project):
    p = db.session.query(models.Project) \
                  .filter(models.Project.slug==project) \
                  .first()

    if p is None:
        return make_response('', 404)

    download_code = request.form.get('download_code')

    if download_code is None:
        return make_response('', 400)

    c = db.session.query(models.DownloadCode) \
                  .filter(models.DownloadCode.project==p) \
                  .filter(models.DownloadCode.code==download_code.lower().strip()) \
                  .first()

    if c is None:
        return make_response('', 404)

    used_tickets = c.times_downloaded()

    if used_tickets >= c.max_downloads:
        return make_response('', 410) # TODO: fijarse si este status code esta bien

    # create new ticket and redirect
    t = models.DownloadTicket(download_code=c,
                              ticket=models.DownloadTicket.get_unique_ticket())
    db.session.add(t)
    db.session.commit()

    download_uri = url_for('.download', project=p.slug, ticket=t.ticket, _external=True)

    if request.is_xhr:
        return make_response('', 200, {
            'X-Download-URI': download_uri,
            'X-Remaining-Downloads': c.max_downloads - c.times_downloaded()
        })
    else:
        return redirect(download_uri)

@mod.route('/<project>/payment', methods=['POST'])
def payment(project):
    p = db.session.query(models.Project) \
                  .filter(models.Project.slug==project) \
                  .first()

    if p is None:
        return make_response('', 404)

    form = forms.Payment(request.form)

    amount = form.data['amount'] if p.is_variable_price else int(p.amount)

    # if not form.validate():
    #     return make_response('', 400)

    mppp = db.session.query(models.MercadoPagoPaymentPreference) \
                     .filter(models.MercadoPagoPaymentPreference.project == p) \
                     .filter(models.MercadoPagoPaymentPreference.amount == amount) \
                     .first()

    # if no preference created for this amount, create a new one
    if mppp is None:
        mppp = models.MercadoPagoPaymentPreference \
                     .save_to_mercadopago(models.MercadoPagoPaymentPreference(project=p,
                                                                              amount=amount))

        db.session.add(mppp)
        db.session.commit()

    mppp_def = json.loads(mppp.definition)

    return redirect(mppp_def['init_point']
                    if not current_app.config.get('MERCADOPAGO_USE_SANDBOX')
                    else mppp_def['sandbox_init_point'])

# http://dev.local.unabanda.cc:5000/p/el-abrigo-del-viento/payment/pending?collection_id=1406141035&collection_status=pending&preference_id=163048080-833a476d-9dd4-430e-b5a1-235fb65ddb39&external_reference=1&payment_type=credit_card
@mod.route('/<project>/payment/<status>')
def payment_confirmation(project, status):
    p = db.session.query(models.Project) \
                  .filter(models.Project.slug==project) \
                  .first()

    if p is None or status not in ('success', 'failure', 'pending'):
        return abort(404)

    if db.session.query(models.MercadoPagoPaymentPreference) \
                 .filter(models.MercadoPagoPaymentPreference.project == p) \
                 .filter(models.MercadoPagoPaymentPreference.payment_preference_id == request.args['preference_id']) \
                 .count() != 1:
        abort(400)

    template_vars = {
        'status': status,
        'project': p,
        'message': '',
    }

    if status == 'success':
        # Check if we received an IPN notification of the successful payment
        cs = db.session.query(mp_models.CollectionStatus) \
                       .join(mp_models.Collection) \
                       .filter(mp_models.Collection.collection_id == request.args['collection_id']) \
                       .filter(mp_models.CollectionStatus.status == 'approved').first()

        if cs is not None:
            download_code = db.session.query(models.DownloadCode) \
                                      .filter(models.DownloadCode.mercadopago_collection_id==cs.collection.id) \
                                      .first()
            template_vars.update({
                'download_code': download_code,
            })
        else:
            # MP reports payment approved (or user trying to forge the query string)
            # but we didn't receive the IPN yet, force 'pending' state.
            template_vars.update({
                'status': 'pending',
                'collection_id': request.args.get('collection_id')
            })

    elif status == 'pending':
        template_vars['collection_id'] = request.args.get('collection_id')
    elif status == 'failure':
        pass

    return make_response(render_template('payment_confirmation.html',
                                         **template_vars))

notplastic/notplastic_site/templates/embed_widget.html
<iframe src="{{ url_for('notplastic_site.index', project=project.slug, _external=True) }}" width="100%" height="400" scrolling="no" frameborder="no"></iframe>

notplastic/notplastic_site/templates/payment_confirmation.html
{% extends "project_landing_layout.html" %}
{% block project_title %}{{ project.name }}{% endblock %}
{% block body %}
<div id="notplastic-download-content">
  {% if status == 'success' %}
  <object data="{{ url_for('notplastic_site.static', filename='img/icon_download.svg') }}" type="image/svg+xml" id="icon-download" class="confirmation-icon"></object>
  {% elif status == 'pending' %}
  <object data="{{ url_for('notplastic_site.static', filename='img/icon_wait.svg') }}" type="image/svg+xml" id="icon-pending" class="confirmation-icon"></object>
  {% elif status == 'failure' %}
  <object data="{{ url_for('notplastic_site.static', filename='img/icon_rejected.svg') }}" type="image/svg+xml" id="icon-failure" class="confirmation-icon"></object>
  {% endif %}
  {% if status == 'success' %}
  <h1>Gracias!</h1>
  <p>Ya podés descargar <em>{{project.name}}</em>. Con el código de descarga <strong>{{download_code}}</strong>, vas a poder descargar el material hasta {{ download_code.max_downloads - 1}} veces más. Te acabamos de enviar el código a la dirección que ingresaste en <em>MercadoPago</em>; si no lo recibiste, por favor chequeá la carpeta de correo no deseado.</p>
  <form action="{{url_for('notplastic_site.validate_download_code', project=project.slug)}}" method="post" id="notplastic-download-form">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="download_code" value="{{ download_code }}" />
    <input type="submit" name="download" value="bajar">
  </form>
  {% elif status == 'pending' %}
  <h1>Esperando</h1>
  <p>Estamos esperando que <em>MercadoPago</em> nos confirme la recepción de tu pago. Si pagaste con tarjeta de crédito o mediante tu cuenta de <em>MercadoPago</em>, vas a recibir por email un código de descarga por email en los próximos minutos. Si elegiste pagar con un cupón o por cajero automático, recibirás tu código cuando completes la operación y <em>MercadoPago</em> nos informe.</p>
  <p>Si no recibís el código dentro de los próximos 3 días hábiles, por favor escribinos a <strong>compras@unabanda.cc</strong>{% if collection_id and collection_id != 'null' %} mencionando el número de operación {{ collection_id }} {% endif %}.</p>
  {% elif status == 'failure' %}
  <h1>Hubo un error</h1>
  <p>Cancelaste el proceso de pago, o hubo un error mientras intentábamos comunicarnos con <em>MercadoPago</em>. Te pedimos que vuelvas a intentar haciendo <a href="{{ url_for('notplastic_site.index', project=project.slug, _external=True) }}">click acá</a>. Si el error persiste, por favor escribinos a <strong>hola@unabanda.cc</strong>.</p>
  {% endif %}
</div>
{% endblock body %}

notplastic/notplastic_site/templates/project_landing.html
{% extends "project_landing_layout.html" %}
{% block head %}
{{ super() }}

<link rel="alternate" type="application/json+oembed"
  href="{{ url_for('notplastic_site.oembed', url=url_for('notplastic_site.index', project=project.slug, _external=True), _external=True) }}"
  title="{{ project.name }} oembed" />
<meta property="twitter:card" content="summary" />
<meta property="twitter:site" content="@unabandacc" />
<meta property="twitter:title" content="{{ project.name}}" />
<meta property="twitter:description" content="¡Bajá '{{ project.name}}' por sólo ${{project.suggested_amount|int}}!" />
<meta property="twitter:image" content="{{ project.background_image_url }}" />
<meta property="twitter:url" content="{{ url_for('notplastic_site.index', project=project.slug, _external=True) }}" />
<meta property="og:title" content="unabanda.cc: {{ project.name }}" />
<meta property="og:description" content="¡Bajá '{{ project.name}}' en unabanda.cc por sólo ${{project.suggested_amount|int}}!" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{{ url_for('notplastic_site.index', project=project.slug, _external=True) }}" />
<meta property="og:image" content="{{ project.background_image_url }}" />
{% endblock %}
{% block project_title %}{{ project.name }}{% endblock %}
{% block body %}
<div id="notplastic-download-content">
  <h1>{{ project.name }}</h1>
  <p class="project-description">{{ project.description }}</p>
  <div class="project-extended-description">{{ project.extended_description|markdown }}</div>
  <hr>
  <h2>Comprar con MercadoPago</h2>
  {% if project.is_variable_price %}
  {% if project.suggested_amount %}
  {% if project.suggested_amount != project.amount %}
  {% set suggested = project.suggested_amount %}
  <p>El precio sugerido es de <strong class="amount">$ {{ project.suggested_amount|int }} (pesos argentinos)</strong>, pero también podés obtener tu descarga aportando desde <strong class="amount">$ {{ project.amount|int }} </strong> hasta <strong class="amount">$ {{ project.max_amount|int }} </strong>.</p>
  {% else %}
  {% set suggested = project.amount %}
  <p>Por un mínimo de <strong class="amount">$ {{ project.amount|int }} (pesos argentinos)</strong>, podés descargar <em>{{ project.name }}</em>. Si querés apoyar nuestro proyecto, podés colaborar con hasta <strong class="max-amount">$ {{ project.max_amount|int }}</strong></p>
  {% endif %}
  {% endif %}
  {% else %}
  <p>Por <strong class="precio">$ {{ project.amount|int }} (pesos argentinos)</strong>, podés descargar <em>{{ project.name }}</em>.</p>
  {% endif %}
  <p>{% if project.max_downloads > 1 %}Además, recibirás un código de descarga que te permitirá descargar el material hasta {{ project.max_downloads - 1 }} {% if project.max_downloads > 2 %}veces{% else %}vez{% endif %}{% endif %} más.</p>
  <form action="{{url_for('notplastic_site.payment', project=project.slug)}}" method="post" id="notplastic-payment-form">
    {{ payment_form.csrf_token }}
    {% if project.is_variable_price %}
    {% if project.max_amount %}
    {{ payment_form.amount(min=project.amount|int, max=project.max_amount|int, value=suggested|int) }}
    {% else %}
    {{ payment_form.amount(min=project.amount|int, max=project.amount*2, value=suggested|int) }}
    {% endif %}
    <output name="total_amount" for="amount"></output>
    <label for="amount">Mové el deslizador para indicar cuánto querés pagar por <em>{{ project.name }}</em></label>
    {% endif %}
    <input type="submit" value="Comprar">
  </form>
  <h2>Código de descarga</h2>
  <p>Si ya tenés un código de descarga, ingresalo aquí.</p>
  <form action="{{url_for('notplastic_site.validate_download_code', project=project.slug)}}" method="post" id="notplastic-download-form">
    {{ download_code_form.csrf_token }}
    {{ download_code_form.download_code(autocomplete='off') }}
    <button type="submit" disabled="disabled">Bajar</button>
    <output for="download_code"></output>
    <!-- input type="submit" value="Bajar" disabled="disabled"-->
  </form>
</div>
{% endblock %}

notplastic/notplastic_site/templates/project_landing_layout.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <title>{% block project_title %}{% endblock %} — unabanda.cc</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('notplastic_site.static', filename='css/project_landing.css') }}">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,900,300' rel='stylesheet' type='text/css'>
    {% if project.background_image_url %}
    <style type="text/css">
      #container {
        background-image: url('{{ project.background_image_url }}');
        background-position: center center;
        background-repeat: no-repeat;
        background-size: cover;
      }
    </style>
    {% endif %}
    {% if project.extra_head_html %}
    {{ project.extra_head_html|safe }}
    {% endif %}
    {% endblock %}
  </head>
  <body>
    <div id="container">
      {% block body %}
      {% endblock %}
    </div>
    <a href="http://unabanda.cc" target="_blank" id="unabanda-logo">unabanda.cc</a>
    {% assets filters="rjsmin", output="gen/packed.js",
    "notplastic_site/js/jquery-1.11.1.js", "notplastic_site/js/spin.js", "notplastic_site/js/project_landing.js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    <!-- button onclick="widget.signin({ scope: 'openid profile' })">Login</button -->
    {% if not config['DEBUG'] %}
    <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '{{ config['GOOGLE_ANALYTICS_ID'] }}', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    </script>
    {% endif %}

  </body>
</html>